### ISSUE TITLE
Err on syscalls

### ISSUE THREAD

**Issue by keyvank** [mahanfr/Nmet#15]
Nice job!

I'm challenging myself to write something complex (E.g a ray-tracer) using your language (https://github.com/keyvank/mndgnmet)! Will probably contribute on Nmet itself too whenever I can!

I'm facing this issue:

```
import "./std/syscalls/file" :: syscall_open

func main() {
    var O_CREAT @int = 0x00000100;
    var O_EXCL @int = 0x00000200;
    var O_WRONLY @int = 0x00000001;
    var S_IRUSR @int = 0x00400;
    var S_IWUSR @int = 0x00200;
    

    syscall_open("file.txt",  O_CREAT | O_EXCL | O_WRONLY,
                S_IRUSR | S_IWUSR);
}
```

The code runs without any error (It doesn't create the file though, I may have given wrong flags)
But when I try to store the result of the syscall in a variable, I'm getting a segmentation fault:

```
import "./std/syscalls/file" :: syscall_open

func main() {
    var O_CREAT @int = 0x00000100;
    var O_EXCL @int = 0x00000200;
    var O_WRONLY @int = 0x00000001;
    var S_IRUSR @int = 0x00400;
    var S_IWUSR @int = 0x00200;
    

    var a = syscall_open("file.txt",  O_CREAT | O_EXCL | O_WRONLY,
                S_IRUSR | S_IWUSR);
}
```

**Comment by mahanfr** [comment]
Hi, Thank You for submitting an issue ❤️ 
This Language is not stable nor complete enough to write anything more complex than provided tests and examples. and most of the std library is not tested yet. but i appropriate reporting any issues that you might find.

I highly advise to use "-nasm" and "-keep-asm" flags while compiling your code to use the nasm assembler insted of the internal assembler which lacks a lot of safety measures. 

I'm currently changing a lot of the core compilation processes to produce more optimized code and segmentation fault occurred because the stack was not restored properly:
the commit [891ee41](https://github.com/mahanfr/Nmet/commit/891ee416f0f52d373d1753f5236dbb3f802d5b71) solved the issue

Please feel free to ask any follow-up questions you might have about this project

**Comment by keyvank** [comment]
Cool,

Anyway, I have always been interested in being part of building a new programming language. I could for example work on a nice standard library for Nmet, whenever the lang itself is ready.
